### ISSUE TITLE
Kraken: Adding a post to an existing forum thread fails

### ISSUE THREAD

**Issue by challfry** [seamonkeysocial/twitarr#328]
I get get a full log if necessary. I'm guessing the "forum" parameter shouldn't be there. It's not a parameter in the URL path, query, nor the JSON body.

Twittar log for failing call from Kraken:

```
Started POST "/api/v2/forums/1004?key=james:1581921512999:2f7258ac5be83d48836e30146da6314072dd8961" for 192.168.1.23 at 2020-02-06 23:23:14 -0800
Processing by Api::V2::ForumsController#new_post as */*
  Parameters: {"text"=>"Also, I misspelled thread.", "photos"=>[], "key"=>"james:1581921512999:2f7258ac5be83d48836e30146da6314072dd8961", "id"=>"1004", "forum"=>{}}
...
  ↳ app/controllers/api/v2/forums_controller.rb:227:in `fetch_forum'
Completed 500 Internal Server Error in 7ms (ActiveRecord: 1.3ms | Allocations: 4731)

NoMethodError (undefined method `forum' for nil:NilClass
Did you mean?  for):

app/controllers/api/v2/forums_controller.rb:240:in `check_locked'
```

Adding new forum posts works from web, here's the relevant log:

```
Started POST "/api/v2/forums/1004" for 127.0.0.1 at 2020-02-06 23:26:42 -0800
Processing by Api::V2::ForumsController#new_post as */*
  Parameters: {"text"=>"Another attempt to add a message to an existing thread.", "id"=>"1004"}
```

**Comment by challfry** [comment]
New info on this: On my developer install, using the web interface, @kvort (an admin user) can add posts to an existing forum thread, but @james (a regular user) cannot.
